### ISSUE TITLE
remote host in xdebug

### ISSUE THREAD

**Issue by Roman-Romanov97** [Cap-Coding/chain_of_responsibility#2]
https://github.com/Cap-Coding/chain_of_responsibility/blob/cafa6a3ea6408fbaa6c5d62b47ebbcd9542e4c03/docker-compose.yml#L14
remote_host=host.docker.internal in Docker 18.03+ 
The host has a changing IP address (or none if you have no network access). We recommend that you connect to the special DNS name host.docker.internal which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Mac.
https://docs.docker.com/docker-for-mac/networking/
is it worth using?

**Comment by kurakin-oleksandr** [comment]
This is pure dev config, xdebug should not be used on production

**Comment by Roman-Romanov97** [comment]
yeah, I understand, but thats config (host.docker.internal) just for local dev env

**Comment by kurakin-oleksandr** [comment]
I didn't get your concern.

**Comment by Roman-Romanov97** [comment]
remote_host=host.docker.internal instead remote_host=docker.for.mac.localhost. Only this moment I wanted to clarify

**Comment by kurakin-oleksandr** [comment]
As far as I know, host name does not really matter. It just should be the same in xdebug configuration and env variable in docker-compose.yml. 
Does not `docker.for.mac.localhost` work for you?

**Comment by Roman-Romanov97** [comment]
> As far as I know, host name does not really matter. It just should be the same in xdebug configuration and env variable in docker-compose.yml.
> Does not `docker.for.mac.localhost` work for you?

Its working on linux mint on my pc, but on my macbook pro it doesn't work. On mac working - docker.for.mac.localhost =)

**Comment by kurakin-oleksandr** [comment]
It's strange, because I work on MacBook Pro and it works. Also I've asked and it works for other people as well.
I'd keep it as it is for now and change if I get more complaints.

**Comment by Roman-Romanov97** [comment]
Thanks =) Thats simple for observe this moment
