### ISSUE TITLE
Why name ending on *Repository?

### ISSUE THREAD

**Issue by Roman-Romanov97** [Cap-Coding/chain_of_responsibility#3]
https://github.com/Cap-Coding/chain_of_responsibility/blob/cafa6a3ea6408fbaa6c5d62b47ebbcd9542e4c03/src/LocationProvider/FavouriteLocationRepository.php#L9

**Comment by kurakin-oleksandr** [comment]
I forgot to rename class. But it's not a problem

**Comment by Roman-Romanov97** [comment]
I got u, thanks =)
